// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SetsnReps.API.Infrastructure;

#nullable disable

namespace SetsnReps.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SetsnReps.Core.Models.Exercise.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes", (string)null);
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Exercise.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrimaryMuscleGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUri")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("PrimaryMuscleGroupId");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Exercise.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups", (string)null);
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Training.ExecutedWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("WeightVolume")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutRoutineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutRoutineId");

                    b.ToTable("ExecutedWorkouts");
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Workout.ExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("ExerciseSets", (string)null);
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Workout.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RestTime")
                        .HasColumnType("integer");

                    b.Property<int>("SelectedExerciseId")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutRoutineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SelectedExerciseId");

                    b.HasIndex("WorkoutRoutineId");

                    b.ToTable("WorkoutExercises", (string)null);
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Workout.WorkoutRoutine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkoutRoutineSetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutRoutineSetId");

                    b.ToTable("WorkoutRoutines", (string)null);
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Workout.WorkoutRoutineSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkoutRoutineSets", (string)null);
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Exercise.Exercise", b =>
                {
                    b.HasOne("SetsnReps.Core.Models.Exercise.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetsnReps.Core.Models.Exercise.MuscleGroup", "PrimaryMuscleGroup")
                        .WithMany()
                        .HasForeignKey("PrimaryMuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("PrimaryMuscleGroup");
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Training.ExecutedWorkout", b =>
                {
                    b.HasOne("SetsnReps.Core.Models.Workout.WorkoutRoutine", "WorkoutRoutine")
                        .WithMany()
                        .HasForeignKey("WorkoutRoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutRoutine");
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Workout.ExerciseSet", b =>
                {
                    b.HasOne("SetsnReps.Core.Models.Workout.WorkoutExercise", null)
                        .WithMany("ExerciseSets")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetsnReps.Core.Models.Workout.ExerciseSet", "WorkoutExercise")
                        .WithMany()
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Workout.WorkoutExercise", b =>
                {
                    b.HasOne("SetsnReps.Core.Models.Workout.WorkoutRoutine", null)
                        .WithMany("Exercises")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetsnReps.Core.Models.Exercise.Exercise", "SelectedExercise")
                        .WithMany()
                        .HasForeignKey("SelectedExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetsnReps.Core.Models.Workout.WorkoutRoutine", "WorkoutRoutine")
                        .WithMany()
                        .HasForeignKey("WorkoutRoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectedExercise");

                    b.Navigation("WorkoutRoutine");
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Workout.WorkoutRoutine", b =>
                {
                    b.HasOne("SetsnReps.Core.Models.Workout.WorkoutRoutineSet", null)
                        .WithMany("WorkoutRoutines")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetsnReps.Core.Models.Workout.WorkoutRoutineSet", "WorkoutRoutineSet")
                        .WithMany()
                        .HasForeignKey("WorkoutRoutineSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutRoutineSet");
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Workout.WorkoutExercise", b =>
                {
                    b.Navigation("ExerciseSets");
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Workout.WorkoutRoutine", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("SetsnReps.Core.Models.Workout.WorkoutRoutineSet", b =>
                {
                    b.Navigation("WorkoutRoutines");
                });
#pragma warning restore 612, 618
        }
    }
}
