
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Sql/megaGymDataset.csv:/tmp/megaGymDataset.csv:ro
      - ./Sql/schema_and_import.sql:/docker-entrypoint-initdb.d/schema_and_import.sql:ro
    restart: unless-stopped

volumes:
  postgres_data: